# Generated by Django 4.2.7 on 2023-12-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customuser_is_active_alter_customuser_temporary"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
