# Generated by Django 5.0 on 2024-01-08 10:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_event_ancestor_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="ancestor_id",
            new_name="ancestor",
        ),
    ]
