# Generated by Django 5.0 on 2024-01-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_rename_ancestor_id_event_ancestor"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
