# Generated by Django 5.0 on 2024-01-08 14:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_participant_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="participant",
            unique_together={("event", "name"), ("event", "user")},
        ),
    ]
