# Generated by Django 5.0 on 2024-01-18 19:39

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_alter_participant_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="draw_date",
            field=models.DateTimeField(default=datetime.date.today, null=True),
        ),
    ]
