# Generated by Django 5.0 on 2024-01-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0006_event_draw_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
