# Generated by Django 5.0 on 2024-02-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0007_event_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_location",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
