# Generated by Django 5.0 on 2024-02-04 20:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0008_event_event_location"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Draw",
        ),
    ]
