# Generated by Django 5.0 on 2024-02-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0010_draw"),
    ]

    operations = [
        migrations.AddField(
            model_name="draw",
            name="collected",
            field=models.BooleanField(default=False),
        ),
    ]
