# Generated by Django 5.0 on 2024-02-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0011_draw_collected"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
