# Generated by Django 5.0 on 2024-04-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0013_emailtask"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtask",
            name="status",
            field=models.CharField(
                choices=[("OK", "US Dollars"), ("NOK", "Not send"), ("PEN", "Pending")],
                max_length=3,
                null=True,
            ),
        ),
    ]
