# Generated by Django 5.0 on 2024-04-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0015_event_confirmed_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="confirmed_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
