# Generated by Django 5.0 on 2024-09-30 16:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0017_alter_exclusion_excluded_participant_whish"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Whish",
            new_name="Wish",
        ),
    ]
